name: Health check

on:
  push:
    branches: 
      - master

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check that the service is running
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://cryptic-wildwood-87634.herokuapp.com/broken
          max-attempts: 3
          retry-delay: 6s